### ISSUE TITLE
*Datatable* - _(Configure Columns)_ - Uncaught error "isDisableSuppressBottomBar" missing setter decorated with@api

### ISSUE THREAD

**Issue by jimrae** [alexed1/LightningFlowComponents#1087]
What Using the Configure Columns to add columns to a table (Opportunity Line item).  when I close the configure columns modal (after I see the "you can close this window" message, I get a Salesforce "Something went Wrong" message.

`Uncaught Error: Invalid attempt to set a new value for property isDisableSuppressBottomBar of [object:vm ers_datatableCPE (1270)] that does not has a setter decorated with @api. throws at https://dtesustainablesolutions--xededev.lightning.force.com/auraFW/javascript/nj61v-uP3bGswhb-VTdr6Q/aura_proddebug.js:12850:11`

### Steps to reproduce

1. Go to 'Datatable in Flow'
2. Click on Configure Columns
3. add columns
4. press "Done"

### Expected behaviour
Should save the columns.

### Actual behaviour
`Uncaught Error: Invalid attempt to set a new value for property isDisableSuppressBottomBar of [object:vm ers_datatableCPE (1270)] that does not has a setter decorated with @api. throws at https://dtesustainablesolutions--xededev.lightning.force.com/auraFW/javascript/nj61v-uP3bGswhb-VTdr6Q/aura_proddebug.js:12850:11`

### Screenshots
![image](https://user-images.githubusercontent.com/1036171/159747792-108a2764-65b4-479b-9c96-3a998a5534b0.png)

**Comment by ericrsmith35** [comment]
What version of Datatable are you running?  What happens if you remove the datatable, save the flow, reopen the flow and then add the datatable back in?

**Comment by jimrae** [comment]
Running 3.5.0 just installed yesterday. I have 2 data tables on the same screen not sure if that matters. Also had a section on the screen as well, but with that no data ever got displayed. I could see it in the console log, but not on screen. 
Once I removed the section the first table shows data. 
Another update on this, I pulled the metadata for the flow into my viscose, and noticed the second table did not have the columns listed. I manually added that xml with the proper fields, and know it renders. I still get that error if I edit the columns, but the ones I added do appear.

**Comment by ericrsmith35** [comment]
Try editing the table with the error and uncheck the Suppress Bottom Bar
option, save, exit, reload and then recheck that option and save.

**Comment by jimrae** [comment]
@ericrsmith35 i do not see a suppress bottom bar option to select or unselect.

**Comment by ericrsmith35** [comment]
That would be the option to Show or Hide the Save/Cancel buttons.

**Comment by jimrae** [comment]
@ericrsmith35 that did seem to address it. not sure why.

**Comment by jcallahan526** [comment]
I am having the same error also running version 3.5.  However I am unable to select the checkbox for "Hide Cancel/Save buttons" - it is greyed out

**Comment by ericrsmith35** [comment]
The Hide Cancel/Save buttons will be greyed out if no columns are selected for editing.

**Comment by davidbingham** [comment]
> The Hide Cancel/Save buttons will be greyed out if no columns are selected for editing.

This error is preventing me from saving my column selections.

**Comment by ericrsmith35** [comment]
Can you temporarily select one column for editing, make the change and then
reset the editing attribute?

**Comment by davidbingham** [comment]
No. Whichever method is responsible for saving my column selections is being interrupted by this error.

**Comment by davidbingham** [comment]
Done that a few times. Ended up commenting out some methods in the js controller, configuring my datatable, and then restoring the methods. 

Still get the error when I try to modify the table but no longer blocked.

**Comment by ericrsmith35** [comment]
What were the methods you had to comment out?

**Comment by mslade24** [comment]
I'm getting the same thing across multiple flows.  It is making the component unusable.  The only workaround is to extract  the flow in VS code, add the Tags for columnFields and redeploy.

**Comment by eclarke12** [comment]
I was able to bypass this issue by commenting the following lines:
https://github.com/alexed1/LightningFlowComponents/blob/2772da904513167296c3676d0d8f886f98c5ba38/flow_screen_components/datatable/force-app/main/default/lwc/ers_datatableCPE/ers_datatableCPE.js#L1120

and

https://github.com/alexed1/LightningFlowComponents/blob/2772da904513167296c3676d0d8f886f98c5ba38/flow_screen_components/datatable/force-app/main/default/lwc/ers_datatableCPE/ers_datatableCPE.js#L1120

As these props have no `@api` setter.

**Comment by davidbingham** [comment]
I'm now using the managed package version of Flow Screen Components so I can't use @eclarke12 's workaround.

**Comment by ericrsmith35** [comment]
This should be fixed in v4.0.9
